# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy report

on:
   pull_request_target:
     types:
       - closed

jobs:
  needs: bild_linting_and_tests
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #    Get Allure history
      #----------------------------------------------
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #----------------------------------------------
      #    Generate allure report
      #----------------------------------------------
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
      #----------------------------------------------
      #    Deploy allure report  on gh-pages
      #----------------------------------------------

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ALLURE_DEPLOY  }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history







