# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Luma bild, test and report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  pull-requests: write
  contents: read
  repository-projects: write
  issues: write


jobs:
  bild_linting_and_tests:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      #----------------------------------------------
      #              Python black and flake8
      #----------------------------------------------
      - name: Python black and flake8
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: ""
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: "--count --benchmark --ignore=E501"
          extra-black-options: ". -S"
          extra-mypy-options: ""
          extra-isort-options: ""
      #----------------------------------------------
      #            install Chrom
      #----------------------------------------------
      - name: Update repo
        run: sudo apt-get update
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v0.0.0
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Load cached Poetry installation
        uses: actions/cache@v3
        with:
          path: ~/.local  # the path depends on the OS
          key: poetry-0  # increment to reset cache
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.3
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
#      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install project dependencies
        run: poetry install
      - name: Allure install
        run: poetry add allure-pytest
      #----------------------------------------------
      #    Run tests and generate junit xml report
      #----------------------------------------------
      - name: Test with pytest
        run: poetry run pytest --junitxml report.xml
      - name: Create test summary
        uses: test-summary/action@v2.0
        with:
          paths: report.xml
        if: always()
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "report.xml"
      - name: Run Test
        if: always()
        run: poetry run pytest --alluredir=allure-results
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #----------------------------------------------
      #    Generate allure report  report
      #----------------------------------------------
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history


      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history





